### ISSUE TITLE
Cuda 

### ISSUE THREAD

**Issue by arita37** [Kocik/cuda-island-genetic#1]
Hello,

Am working to do it in pthon version.
Just wondering if I can you some questions ?

Thanks, regards

**Comment by Kocik** [comment]
Hi,
not sure if I'm the best source You can find on the topic - that was more of an experiment, still need to finish migration part. 

But sure, hit me. What do you need to know?

**Comment by arita37** [comment]
Hello,

How is the increase in speed up ?
Did you test on becnhmarks functions ?
Thanks, regards

**Comment by Kocik** [comment]
Hi, sorry for the delay. Unfortunately, I did not make any benchmarks for that.

Question is what do you want to compare it to? Other CUDA implementation? Single-thread implementation on regular processor?
I guess that would make sense to compare regular genetic with computations paralelized on CUDA as much as they can be parallelized. Then you can test the population as big as will fit in the memory of the graphic card and compare. Then again - my implementation assumes that the population will not fit in the memory and the data will have to be exchanged with the hard drive. That way you can have virtually infinite. Bottleneck being data transfer.

**Comment by arita37** [comment]
Hello,

Thanks for replying.
Just wondering how the objective function is evaluated ?
 Is it in GPU or in CPU side.

Do we need to compile every time a new objective function is written ?
Is there a way to use a pointer, so only objective function needs to be re-implemented....

**Comment by Kocik** [comment]
There is this function that computes the fitness:

```
__device__ float
fitnessValue(float *baseSizes, float *baseValues, unsigned char *phenotype, float backpackMaxSize)
```

It is evaluated on the device in parallel with other islands computed at the time an the device. It computes value for a single phenotype so you can just override it.

Could we use a pointer? It is not implemented now, but it should be possible. This should help: 
http://stackoverflow.com/questions/31057870/passing-host-function-as-a-function-pointer-in-global-or-device-function

**Comment by arita37** [comment]
Hello,

Sounds interesting.
I have just seen Open ACC
https://devblogs.nvidia.com/parallelforall/7-powerful-new-features-openacc-2-0/

framework to have single code.

It might be interesting to put into OpenACC.

Having one layer of abstraction would make the code easier to modify.

Thanks

On 06 Oct 2016, at 17:06, Kocik notifications@github.com wrote:

There is this function that computes the fitness:

**device** float
fitnessValue(float *baseSizes, float *baseValues, unsigned char *phenotype, float backpackMaxSize)
It is evaluated on the device in parallel with other islands computed at the time an the device. It computes value for a single phenotype so you can just override it.

Could we use a pointer? It is not implemented now, but it should be possible. This should help: 
http://stackoverflow.com/questions/31057870/passing-host-function-as-a-function-pointer-in-global-or-device-function

―

**Comment by Kocik** [comment]
I can imagine there are situations where you want the control and optimizations of native code.

Bu I agree that using abstraction, should result in less bugs and as well as saving you a ton of time to develop/modify the solution, while still giving good enough performance boost - which will be probably preferable in most use cases. And portability is a BIG plus. Using cuda you depend on access to Nvidia device.
